spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppyz
    username: root
    password: root
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop

jackson:
  visibility.field: any
  visibility.getter: none
  visibility.setter: none
  visibility.is-getter: none
